// EDITAR: altere os exemplos abaixo. Para fotos, use ficheiros na pasta assets/ ou URLs https://...
// WhatsApp: escreva indicativo + número, só algarismos, por exemplo 351912345678.
window.CL_CONFIG = { whatsapp: "" };
window.CL_PRODUCTS = [
 {type:"SPC",name:"Pavimento SPC Carvalho Natural",description:"Referência de demonstração. Substitua por descrição e especificações reais.",image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80"},
 {type:"EPC",name:"EPC Carvalho Claro",description:"Referência de demonstração. Substitua por descrição e especificações reais.",image:"https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80"},
 {type:"SPC",name:"SPC Carvalho Areia",description:"Referência de demonstração. Preço sob consulta.",image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80"},
 {type:"SPC",
  name:"Pavimento SPC Carvalho Creme",
  description:"Pavimento da coleção Carvalho Creme. Consulte-nos para informações e orçamento.",
  image:"assets/carvalho-creme.png"},
{type:"SPC",
  name:"Pavimento SPC Carvalho Mel",
  description:"Pavimento da coleção Carvalho Mel. Consulte-nos para informações e orçamento.",
  image:"https://images.unsplash.com/photo-160067678939e-8ca6c2511c8?auto=format&fit=crop&w=900&q=80"},
{type:"SPC",
  name:"Pavimento SPC Carvalho Branco",
  description:"Pavimento da coleção Carvalho Branco. Consulte-nos para informações e orçamento.",
  image:"https://images.unsplash.com/photo-160067678939e-8ca6c2511c8?auto=format&fit=crop&w=900&q=80"},
{type:"WPC",
  name:"Deck Compósito Coextrudido",
  description:"Solução de deck compósito para espaços exteriores. Consulte-nos para informações e orçamento.",
  image:"https://images.unsplash.com/photo-160067678939e-8ca6c2511c8?auto=format&fit=crop&w=900&q=80"},
{type:"WPC",
  name:"Deck Compósito",
  description:"Deck compósito para projetos exteriores. Consulte-nos para informações e orçamento.",
  image:"https://images.unsplash.com/photo-160067678939e-8ca6c2511c8?auto=format&fit=crop&w=900&q=80"},
{type:"WPC",
  name:"Revestimento Exterior Compósito Ripado",
  description:"Revestimento exterior de compósito ripado. Consulte-nos para informações e orçamento.",
  image:"https://images.unsplash.com/photo-160067678939e-8ca6c2511c8?auto=format&fit=crop&w=900&q=80"},
{type:"WPC",
  name:"Revestimento de Parede WPC Coextrudido",
  description:"Revestimento de parede WPC coextrudido. Consulte-nos para informações e orçamento.",
  image:"https://images.unsplash.com/photo-160067678939e-8ca6c2511c8?auto=format&fit=crop&w=900&q=80"}
];
